"""Implementando role 3.0

Revision ID: 93242267192a
Revises: 3f2e5e86b23b
Create Date: 2025-06-20 15:23:08.286170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93242267192a'
down_revision = '3f2e5e86b23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
